backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "chapters.json"
        label: "Book Chapters"
        name: "chapters"
        fields:
          - {label: "Chapters List", name: "chapters", widget: "list", fields: [
              {label: "Title", name: "title", widget: "string"},
              {label: "Content", name: "content", widget: "text"}
            ]}
      - file: "guestbook.json"
        label: "Guestbook Entries"
        name: "guestbook"
        fields:
          - {label: "Entries List", name: "entries", widget: "list", fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Message", name: "message", widget: "text"}
            ]}
